# Generated by Django 5.1.2 on 2026-10-08 08:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "football_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Permanent, system-generated identifier. Format: CF-XXXXXXXX.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "preferred_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("CB", "Centre Back"),
                            ("LB", "Left Back"),
                            ("RB", "Right Back"),
                            ("LWB", "Left Wing Back"),
                            ("RWB", "Right Wing Back"),
                            ("CDM", "Defensive Midfielder"),
                            ("CM", "Central Midfielder"),
                            ("CAM", "Attacking Midfielder"),
                            ("LM", "Left Midfielder"),
                            ("RM", "Right Midfielder"),
                            ("LW", "Left Winger"),
                            ("RW", "Right Winger"),
                            ("ST", "Striker"),
                            ("CF", "Centre Forward"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                ("profile_photo_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "players", "ordering": ["-created_at"],},
        ),
    ]
