# Generated by Django 5.1.2 on 2026-10-08 11:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        ("development", "0001_initial"),
        ("players", "0002_player_user"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("TACTICAL", "Tactical"),
                            ("PHYSICAL", "Physical"),
                            ("MENTAL", "Mental"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "exercises", "ordering": ["category", "name"],},
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("training_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_sessions",
                        to="academies.academy",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_sessions_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "focus_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="training_sessions",
                        to="development.skill",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_sessions",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "training_sessions",
                "ordering": ["-training_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSessionExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Display order within the session (1-based).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_exercises",
                        to="training.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_exercises",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={"db_table": "training_session_exercises", "ordering": ["order"],},
        ),
        migrations.CreateModel(
            name="TrainingAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_attendance",
                        to="players.player",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "db_table": "training_attendance",
                "ordering": ["-recorded_at"],
                "unique_together": {("session", "player")},
            },
        ),
    ]
