# Generated by Django 5.1.2 on 2026-10-08 11:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        ("players", "0002_player_user"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opponent_name", models.CharField(max_length=200)),
                ("match_date", models.DateField()),
                ("venue", models.CharField(blank=True, default="", max_length=200)),
                (
                    "competition",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "home_away",
                    models.CharField(
                        choices=[("HOME", "Home"), ("AWAY", "Away")], max_length=4
                    ),
                ),
                ("team_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "opponent_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="academies.academy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-match_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchPlayerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started", models.BooleanField(default=False)),
                (
                    "minutes_played",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("goals", models.PositiveSmallIntegerField(default=0)),
                ("assists", models.PositiveSmallIntegerField(default=0)),
                ("shots", models.PositiveSmallIntegerField(default=0)),
                ("shots_on_target", models.PositiveSmallIntegerField(default=0)),
                ("passes_attempted", models.PositiveSmallIntegerField(default=0)),
                ("passes_completed", models.PositiveSmallIntegerField(default=0)),
                ("key_passes", models.PositiveSmallIntegerField(default=0)),
                ("dribbles", models.PositiveSmallIntegerField(default=0)),
                ("tackles", models.PositiveSmallIntegerField(default=0)),
                ("interceptions", models.PositiveSmallIntegerField(default=0)),
                ("yellow_cards", models.PositiveSmallIntegerField(default=0)),
                ("red_cards", models.PositiveSmallIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coach rating on a 0–10 scale.",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                ("coach_comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="matches.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_stats",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "match_player_stats",
                "ordering": ["-created_at"],
                "unique_together": {("match", "player")},
            },
        ),
    ]
